version: '3.8'

services:
  backend:
    build:
      context: ./nest-my-favorite-products
    container_name: nest-backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=nest-my-favorite-products-mysql
    depends_on:
      - mysql
    volumes:
      - ./nest-my-favorite-products:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0.42
    container_name: nest-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-my-favorite-products-mysql
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: